language: go

go:
  - "1.9"
  - "1.10.x"
  - master

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure -v -vendor-only

script:
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
